sonar.projectKey=jmpangilinan_inventory-api
sonar.organization=jmpangilinan
sonar.projectName=Inventory API

sonar.sources=app,routes
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**,config/**
sonar.coverage.exclusions=config/**,routes/**,database/**,resources/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=coverage.xml

sonar.sourceEncoding=UTF-8
